import type { FontFamily } from '../../types/font';

export const VERIFIED_GOOGLE_FONTS: FontFamily[] = [
  {
    id: 'inter',
    family: 'Inter',
    category: 'sans-serif',
    designer: 'Rasmus Andersson',
    variants: [
      { weight: 100, style: 'normal' },
      { weight: 200, style: 'normal' },
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 800, style: 'normal' },
      { weight: 900, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic', 'greek', 'vietnamese'],
    version: 'v13',
    lastModified: '2024-05-10',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Inter',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap\');',
    fontFamilyCss: 'font-family: \'Inter\', sans-serif;',
    variable: true,
    description: 'Inter is a variable font family crafted for computer screens, featuring tall x-height to aid in legibility of mixed-case text.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'low',
      proportions: 'regular',
      xHeight: 'high',
      aperture: 'semi-closed',
      avgAspect: 0.62,
      strokeWidthRatio: 0.12
    },
    commercialAlternativesFor: ['Helvetica', 'Helvetica Neue', 'San Francisco', 'Arial'],
    recommendedPairings: ['Playfair Display', 'Merriweather', 'Lora', 'Space Mono']
  },
  {
    id: 'roboto',
    family: 'Roboto',
    category: 'sans-serif',
    designer: 'Christian Robertson',
    variants: [
      { weight: 100, style: 'normal' },
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 900, style: 'normal' },
      { weight: 400, style: 'italic' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic', 'greek'],
    version: 'v30',
    lastModified: '2024-03-12',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Roboto',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap\');',
    fontFamilyCss: 'font-family: \'Roboto\', sans-serif;',
    variable: false,
    description: 'Roboto has a dual nature. It has a mechanical skeleton and the forms are largely geometric with friendly, open curves.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'low',
      proportions: 'regular',
      xHeight: 'medium',
      aperture: 'open',
      avgAspect: 0.60,
      strokeWidthRatio: 0.11
    },
    commercialAlternativesFor: ['Helvetica', 'Univers', 'DIN'],
    recommendedPairings: ['Roboto Slab', 'Merriweather', 'Playfair Display']
  },
  {
    id: 'montserrat',
    family: 'Montserrat',
    category: 'sans-serif',
    designer: 'Julieta Ulanovsky',
    variants: [
      { weight: 100, style: 'normal' },
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 800, style: 'normal' },
      { weight: 900, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic', 'vietnamese'],
    version: 'v26',
    lastModified: '2024-04-01',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Montserrat',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&display=swap\');',
    fontFamilyCss: 'font-family: \'Montserrat\', sans-serif;',
    variable: true,
    description: 'Inspired by the historic posters and signs in the traditional Montserrat neighborhood of Buenos Aires. Renowned geometric proportions.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'none',
      proportions: 'geometric',
      xHeight: 'medium',
      aperture: 'open',
      avgAspect: 0.68,
      strokeWidthRatio: 0.13
    },
    commercialAlternativesFor: ['Gotham', 'Futura', 'Proxima Nova', 'Avenir'],
    recommendedPairings: ['Lora', 'Merriweather', 'Cormorant Garamond']
  },
  {
    id: 'poppins',
    family: 'Poppins',
    category: 'sans-serif',
    designer: 'Indian Type Foundry, Jonny Pinhorn',
    variants: [
      { weight: 100, style: 'normal' },
      { weight: 200, style: 'normal' },
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 800, style: 'normal' },
      { weight: 900, style: 'normal' }
    ],
    subsets: ['devanagari', 'latin', 'latin-ext'],
    version: 'v21',
    lastModified: '2024-02-18',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Poppins',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap\');',
    fontFamilyCss: 'font-family: \'Poppins\', sans-serif;',
    variable: false,
    description: 'Geometric sans serif typeface with pure circular letterforms and clean horizontal and vertical terminals.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'none',
      proportions: 'geometric',
      xHeight: 'high',
      aperture: 'open',
      avgAspect: 0.69,
      strokeWidthRatio: 0.12
    },
    commercialAlternativesFor: ['Futura', 'Avant Garde', 'Gilroy', 'Avenir'],
    recommendedPairings: ['Playfair Display', 'Merriweather', 'PT Serif']
  },
  {
    id: 'plus-jakarta-sans',
    family: 'Plus Jakarta Sans',
    category: 'sans-serif',
    designer: 'Gumpita Rahayu, Tokotype',
    variants: [
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 800, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext', 'vietnamese'],
    version: 'v8',
    lastModified: '2024-03-20',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Plus+Jakarta+Sans',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap\');',
    fontFamilyCss: 'font-family: \'Plus Jakarta Sans\', sans-serif;',
    variable: true,
    description: 'A fresh, contemporary take on neo-grotesque sans serif with subtle quirky details, beloved in modern SaaS and digital product design.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'low',
      proportions: 'geometric',
      xHeight: 'high',
      aperture: 'open',
      avgAspect: 0.65,
      strokeWidthRatio: 0.12
    },
    commercialAlternativesFor: ['Circular', 'Sharp Sans', 'Proxima Nova'],
    recommendedPairings: ['Newsreader', 'Fraunces', 'Space Mono']
  },
  {
    id: 'dm-sans',
    family: 'DM Sans',
    category: 'sans-serif',
    designer: 'Colophon Foundry',
    variants: [
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 700, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext'],
    version: 'v14',
    lastModified: '2024-01-15',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/DM+Sans',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap\');',
    fontFamilyCss: 'font-family: \'DM Sans\', sans-serif;',
    variable: true,
    description: 'Low-contrast geometric sans-serif intended for small text sizes, with balanced proportions and clean aesthetic.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'none',
      proportions: 'geometric',
      xHeight: 'high',
      aperture: 'open',
      avgAspect: 0.64,
      strokeWidthRatio: 0.11
    },
    commercialAlternativesFor: ['Neuzeit Grotesk', 'Avenir', 'Founders Grotesk'],
    recommendedPairings: ['DM Serif Display', 'Lora', 'Playfair Display']
  },
  {
    id: 'manrope',
    family: 'Manrope',
    category: 'sans-serif',
    designer: 'Mikhail Sharanda',
    variants: [
      { weight: 200, style: 'normal' },
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 800, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic', 'greek'],
    version: 'v15',
    lastModified: '2024-03-05',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Manrope',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap\');',
    fontFamilyCss: 'font-family: \'Manrope\', sans-serif;',
    variable: true,
    description: 'An open-source modern geometric sans-serif that fuses semi-rounded elements with high readability and crisp digits.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'low',
      proportions: 'regular',
      xHeight: 'high',
      aperture: 'open',
      avgAspect: 0.63,
      strokeWidthRatio: 0.12
    },
    commercialAlternativesFor: ['Euclid Circular', 'Circular Std', 'FF Mark'],
    recommendedPairings: ['Playfair Display', 'Cinzel', 'EB Garamond']
  },
  {
    id: 'open-sans',
    family: 'Open Sans',
    category: 'sans-serif',
    designer: 'Steve Matteson',
    variants: [
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 800, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic', 'greek', 'hebrew', 'vietnamese'],
    version: 'v36',
    lastModified: '2024-02-28',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Open+Sans',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700;800&display=swap\');',
    fontFamilyCss: 'font-family: \'Open Sans\', sans-serif;',
    variable: true,
    description: 'Humanist sans serif typeface designed with an upright stress, open forms, and a neutral, friendly appearance.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'low',
      proportions: 'regular',
      xHeight: 'high',
      aperture: 'open',
      avgAspect: 0.61,
      strokeWidthRatio: 0.11
    },
    commercialAlternativesFor: ['Frutiger', 'Myriad Pro', 'Lucida Grande'],
    recommendedPairings: ['Merriweather', 'Lora', 'Playfair Display']
  },
  {
    id: 'lato',
    family: 'Lato',
    category: 'sans-serif',
    designer: 'Łukasz Dziedzic',
    variants: [
      { weight: 100, style: 'normal' },
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 900, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext'],
    version: 'v24',
    lastModified: '2024-01-20',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Lato',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap\');',
    fontFamilyCss: 'font-family: \'Lato\', sans-serif;',
    variable: false,
    description: 'Lato ("Summer" in Polish) balances semi-rounded details with classical proportions to convey warmth and stability.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'low',
      proportions: 'regular',
      xHeight: 'medium',
      aperture: 'open',
      avgAspect: 0.61,
      strokeWidthRatio: 0.11
    },
    commercialAlternativesFor: ['Gill Sans', 'Myriad', 'Frutiger'],
    recommendedPairings: ['Playfair Display', 'Merriweather', 'Cinzel']
  },
  {
    id: 'raleway',
    family: 'Raleway',
    category: 'sans-serif',
    designer: 'Matt McInerney, Pablo Impallari, Rodrigo Fuenzalida',
    variants: [
      { weight: 100, style: 'normal' },
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 900, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic'],
    version: 'v29',
    lastModified: '2024-02-05',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Raleway',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500;600;700;900&display=swap\');',
    fontFamilyCss: 'font-family: \'Raleway\', sans-serif;',
    variable: true,
    description: 'An elegant neo-grotesque sans serif with a distinctive criss-cross \'W\' and artistic personality for headings and identity.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'low',
      proportions: 'geometric',
      xHeight: 'low',
      aperture: 'open',
      avgAspect: 0.64,
      strokeWidthRatio: 0.10
    },
    commercialAlternativesFor: ['Century Gothic', 'Avant Garde', 'Neutraface'],
    recommendedPairings: ['Merriweather', 'Playfair Display', 'Lora']
  },
  {
    id: 'oswald',
    family: 'Oswald',
    category: 'sans-serif',
    designer: 'Vernon Adams',
    variants: [
      { weight: 200, style: 'normal' },
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic', 'vietnamese'],
    version: 'v49',
    lastModified: '2024-02-12',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Oswald',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap\');',
    fontFamilyCss: 'font-family: \'Oswald\', sans-serif;',
    variable: true,
    description: 'A rework of the classic Alternate Gothic style re-proportioned for digital screens. Strong condensed vertical rhythm.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'low',
      proportions: 'condensed',
      xHeight: 'high',
      aperture: 'semi-closed',
      avgAspect: 0.44,
      strokeWidthRatio: 0.14
    },
    commercialAlternativesFor: ['Alternate Gothic', 'Impact', 'DIN Condensed'],
    recommendedPairings: ['Open Sans', 'Roboto', 'Lora']
  },
  {
    id: 'playfair-display',
    family: 'Playfair Display',
    category: 'serif',
    designer: 'Claus Eggers Sørensen',
    variants: [
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 800, style: 'normal' },
      { weight: 900, style: 'normal' },
      { weight: 400, style: 'italic' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic', 'vietnamese'],
    version: 'v37',
    lastModified: '2024-03-15',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Playfair+Display',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,600;0,700;0,800;1,400&display=swap\');',
    fontFamilyCss: 'font-family: \'Playfair Display\', serif;',
    variable: true,
    description: 'Transitional serif with high stroke contrast inspired by John Baskerville and European Enlightenment typography. Ideal for luxury & editorial titles.',
    typographicMetrics: {
      serif: 'bracketed',
      contrast: 'high',
      proportions: 'regular',
      xHeight: 'medium',
      aperture: 'closed',
      avgAspect: 0.65,
      strokeWidthRatio: 0.14
    },
    commercialAlternativesFor: ['Bodoni', 'Didot', 'Baskerville', 'Playbill'],
    recommendedPairings: ['Inter', 'Montserrat', 'Plus Jakarta Sans', 'Open Sans']
  },
  {
    id: 'merriweather',
    family: 'Merriweather',
    category: 'serif',
    designer: 'Sorkin Type',
    variants: [
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 900, style: 'normal' },
      { weight: 400, style: 'italic' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic'],
    version: 'v30',
    lastModified: '2024-02-10',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Merriweather',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;1,400&display=swap\');',
    fontFamilyCss: 'font-family: \'Merriweather\', serif;',
    variable: false,
    description: 'Designed to be a text face that is pleasant to read on screens, with very large x-height, mild diagonal stress, and sturdy serifs.',
    typographicMetrics: {
      serif: 'bracketed',
      contrast: 'medium',
      proportions: 'regular',
      xHeight: 'high',
      aperture: 'open',
      avgAspect: 0.62,
      strokeWidthRatio: 0.13
    },
    commercialAlternativesFor: ['Georgia', 'Charter', 'Palatino'],
    recommendedPairings: ['Open Sans', 'Roboto', 'Montserrat']
  },
  {
    id: 'lora',
    family: 'Lora',
    category: 'serif',
    designer: 'Cyreal',
    variants: [
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 400, style: 'italic' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic', 'vietnamese'],
    version: 'v35',
    lastModified: '2024-03-01',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Lora',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap\');',
    fontFamilyCss: 'font-family: \'Lora\', serif;',
    variable: true,
    description: 'A contemporary serif with roots in calligraphy. It has moderate contrast and brushed curves that look great in literary paragraphs.',
    typographicMetrics: {
      serif: 'bracketed',
      contrast: 'medium',
      proportions: 'regular',
      xHeight: 'medium',
      aperture: 'open',
      avgAspect: 0.63,
      strokeWidthRatio: 0.12
    },
    commercialAlternativesFor: ['Minion Pro', 'Times New Roman', 'Galliard'],
    recommendedPairings: ['Inter', 'DM Sans', 'Poppins']
  },
  {
    id: 'eb-garamond',
    family: 'EB Garamond',
    category: 'serif',
    designer: 'Georg Duffner',
    variants: [
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 800, style: 'normal' },
      { weight: 400, style: 'italic' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic', 'greek', 'vietnamese'],
    version: 'v27',
    lastModified: '2024-02-14',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/EB+Garamond',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap\');',
    fontFamilyCss: 'font-family: \'EB Garamond\', serif;',
    variable: true,
    description: 'A revival of Claude Garamont\'s famous humanistic sixteenth-century humanist typeface, bringing classic bookish beauty to digital screens.',
    typographicMetrics: {
      serif: 'bracketed',
      contrast: 'medium',
      proportions: 'regular',
      xHeight: 'low',
      aperture: 'open',
      avgAspect: 0.58,
      strokeWidthRatio: 0.10
    },
    commercialAlternativesFor: ['Adobe Garamond', 'Garamond Premier', 'Sabon'],
    recommendedPairings: ['Montserrat', 'Inter', 'Cinzel']
  },
  {
    id: 'cinzel',
    family: 'Cinzel',
    category: 'serif',
    designer: 'Natanael Gama',
    variants: [
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 800, style: 'normal' },
      { weight: 900, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext'],
    version: 'v23',
    lastModified: '2024-01-10',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Cinzel',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700;800;900&display=swap\');',
    fontFamilyCss: 'font-family: \'Cinzel\', serif;',
    variable: true,
    description: 'Inspired by first-century Roman inscriptional capitals and classical proportions, ideal for cinematic titles, luxury brands, and monuments.',
    typographicMetrics: {
      serif: 'bracketed',
      contrast: 'high',
      proportions: 'wide',
      xHeight: 'medium',
      aperture: 'open',
      avgAspect: 0.72,
      strokeWidthRatio: 0.13
    },
    commercialAlternativesFor: ['Trajan', 'Columna', 'Friz Quadrata'],
    recommendedPairings: ['Lora', 'Fauna One', 'Inter']
  },
  {
    id: 'cormorant-garamond',
    family: 'Cormorant Garamond',
    category: 'serif',
    designer: 'Christian Thalmann',
    variants: [
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 400, style: 'italic' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic', 'vietnamese'],
    version: 'v16',
    lastModified: '2024-03-08',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Cormorant+Garamond',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;0,700;1,400&display=swap\');',
    fontFamilyCss: 'font-family: \'Cormorant Garamond\', serif;',
    variable: true,
    description: 'Graceful, high-contrast serif display family developed by Catharsis Fonts, carrying expressive curves, sharp terminals, and opulent flourishes.',
    typographicMetrics: {
      serif: 'hairline',
      contrast: 'high',
      proportions: 'regular',
      xHeight: 'low',
      aperture: 'closed',
      avgAspect: 0.59,
      strokeWidthRatio: 0.10
    },
    commercialAlternativesFor: ['Didot', 'ITC Garamond', 'Walbaum'],
    recommendedPairings: ['Montserrat', 'Inter', 'Plus Jakarta Sans']
  },
  {
    id: 'jetbrains-mono',
    family: 'JetBrains Mono',
    category: 'monospace',
    designer: 'JetBrains',
    variants: [
      { weight: 100, style: 'normal' },
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 800, style: 'normal' },
      { weight: 400, style: 'italic' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic', 'greek'],
    version: 'v18',
    lastModified: '2024-04-10',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/JetBrains+Mono',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,400;0,500;0,700;1,400&display=swap\');',
    fontFamilyCss: 'font-family: \'JetBrains Mono\', monospace;',
    variable: true,
    description: 'A typeface crafted specifically for developers, with increased letter height, distinct symbol shapes, and 140+ code ligatures.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'none',
      proportions: 'regular',
      xHeight: 'high',
      aperture: 'open',
      avgAspect: 0.60,
      strokeWidthRatio: 0.12
    },
    commercialAlternativesFor: ['Operator Mono', 'Dank Mono', 'Consolas', 'Menlo'],
    recommendedPairings: ['Inter', 'Plus Jakarta Sans', 'DM Sans']
  },
  {
    id: 'space-mono',
    family: 'Space Mono',
    category: 'monospace',
    designer: 'Colophon Foundry',
    variants: [
      { weight: 400, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 400, style: 'italic' }
    ],
    subsets: ['latin', 'latin-ext', 'vietnamese'],
    version: 'v13',
    lastModified: '2024-01-14',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Space+Mono',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400&display=swap\');',
    fontFamilyCss: 'font-family: \'Space Mono\', monospace;',
    variable: false,
    description: 'An original fixed-width family with 1960s sci-fi aesthetic, combines brutalist geometric forms with typewriter mechanical quirks.',
    typographicMetrics: {
      serif: 'slab',
      contrast: 'none',
      proportions: 'regular',
      xHeight: 'medium',
      aperture: 'open',
      avgAspect: 0.60,
      strokeWidthRatio: 0.12
    },
    commercialAlternativesFor: ['Apercu Mono', 'Pitch', 'Monaco'],
    recommendedPairings: ['Space Grotesk', 'Inter', 'Work Sans']
  },
  {
    id: 'fira-code',
    family: 'Fira Code',
    category: 'monospace',
    designer: 'Nikita Prokopov',
    variants: [
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic', 'greek'],
    version: 'v22',
    lastModified: '2024-03-18',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Fira+Code',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500;600;700&display=swap\');',
    fontFamilyCss: 'font-family: \'Fira Code\', monospace;',
    variable: true,
    description: 'Monospaced font with programming ligatures, designed to turn multiple-character symbols into single logical glyphs for fast reading.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'none',
      proportions: 'regular',
      xHeight: 'medium',
      aperture: 'open',
      avgAspect: 0.60,
      strokeWidthRatio: 0.12
    },
    commercialAlternativesFor: ['PragmataPro', 'Monaco', 'Courier New'],
    recommendedPairings: ['Fira Sans', 'Inter', 'Roboto']
  },
  {
    id: 'bebas-neue',
    family: 'Bebas Neue',
    category: 'display',
    designer: 'Ryoichi Tsunekawa',
    variants: [
      { weight: 400, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext'],
    version: 'v10',
    lastModified: '2024-02-01',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Bebas+Neue',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap\');',
    fontFamilyCss: 'font-family: \'Bebas Neue\', sans-serif;',
    variable: false,
    description: 'The world\'s favorite bold, condensed sans-serif all-caps display typeface, used ubiquitously across posters, packaging, and sports media.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'none',
      proportions: 'condensed',
      xHeight: 'high',
      aperture: 'closed',
      avgAspect: 0.42,
      strokeWidthRatio: 0.16
    },
    commercialAlternativesFor: ['Compacta', 'Haettenschweiler', 'Helvetica Inserat'],
    recommendedPairings: ['Montserrat', 'Roboto', 'Open Sans']
  },
  {
    id: 'anton',
    family: 'Anton',
    category: 'display',
    designer: 'Vernon Adams',
    variants: [
      { weight: 400, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext', 'vietnamese'],
    version: 'v25',
    lastModified: '2024-01-25',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Anton',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Anton&display=swap\');',
    fontFamilyCss: 'font-family: \'Anton\', sans-serif;',
    variable: false,
    description: 'A reworking of a traditional advertising grotesque typeface designed specifically for punchy headlines and impact statements.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'low',
      proportions: 'condensed',
      xHeight: 'high',
      aperture: 'closed',
      avgAspect: 0.46,
      strokeWidthRatio: 0.20
    },
    commercialAlternativesFor: ['Impact', 'Placard Bold', 'Futura Bold Condensed'],
    recommendedPairings: ['Roboto', 'Open Sans', 'Lato']
  },
  {
    id: 'pacifico',
    family: 'Pacifico',
    category: 'handwriting',
    designer: 'Vernon Adams',
    variants: [
      { weight: 400, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic', 'vietnamese'],
    version: 'v22',
    lastModified: '2024-02-19',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Pacifico',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Pacifico&display=swap\');',
    fontFamilyCss: 'font-family: \'Pacifico\', cursive;',
    variable: false,
    description: 'An original and fun brush script font inspired by 1950s American surf culture and neon roadside signage.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'medium',
      proportions: 'regular',
      xHeight: 'medium',
      aperture: 'open',
      avgAspect: 0.65,
      strokeWidthRatio: 0.14
    },
    commercialAlternativesFor: ['Brush Script', 'Kaufmann', 'Snell Roundhand'],
    recommendedPairings: ['Open Sans', 'Quicksand', 'Lato']
  },
  {
    id: 'caveat',
    family: 'Caveat',
    category: 'handwriting',
    designer: 'Impallari Type',
    variants: [
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext', 'cyrillic'],
    version: 'v18',
    lastModified: '2024-03-02',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Caveat',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Caveat:wght@400;600;700&display=swap\');',
    fontFamilyCss: 'font-family: \'Caveat\', cursive;',
    variable: true,
    description: 'A playful and uninhibited handwriting font with open strokes and friendly curves, excellent for annotations and quotes.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'low',
      proportions: 'regular',
      xHeight: 'medium',
      aperture: 'open',
      avgAspect: 0.55,
      strokeWidthRatio: 0.11
    },
    commercialAlternativesFor: ['Bradley Hand', 'Segoe Script', 'Mistral'],
    recommendedPairings: ['Inter', 'Nunito', 'Roboto']
  },
  {
    id: 'space-grotesk',
    family: 'Space Grotesk',
    category: 'sans-serif',
    designer: 'Florian Karsten',
    variants: [
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext', 'vietnamese'],
    version: 'v16',
    lastModified: '2024-02-12',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Space+Grotesk',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap\');',
    fontFamilyCss: 'font-family: \'Space Grotesk\', sans-serif;',
    variable: true,
    description: 'A proportional sans-serif variant based on Colophon Foundry\'s Space Mono, retaining idiosyncratic mechanical details.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'low',
      proportions: 'wide',
      xHeight: 'high',
      aperture: 'open',
      avgAspect: 0.68,
      strokeWidthRatio: 0.12
    },
    commercialAlternativesFor: ['Syne', 'Apercu', 'Favorit'],
    recommendedPairings: ['Space Mono', 'Inter', 'Newsreader']
  },
  {
    id: 'syne',
    family: 'Syne',
    category: 'display',
    designer: 'Bonjour Monde, Lucas Descroix',
    variants: [
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 800, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext'],
    version: 'v12',
    lastModified: '2024-03-10',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Syne',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&display=swap\');',
    fontFamilyCss: 'font-family: \'Syne\', sans-serif;',
    variable: true,
    description: 'Originally designed for an art center, Syne features wide, avant-garde letterforms that stretch dramatically at heavier weights.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'none',
      proportions: 'wide',
      xHeight: 'high',
      aperture: 'open',
      avgAspect: 0.76,
      strokeWidthRatio: 0.14
    },
    commercialAlternativesFor: ['Druk Wide', 'Monument Extended', 'Dada Grotesk'],
    recommendedPairings: ['Inter', 'Space Mono', 'Work Sans']
  },
  {
    id: 'outfit',
    family: 'Outfit',
    category: 'sans-serif',
    designer: 'Rodrigo Fuenzalida',
    variants: [
      { weight: 100, style: 'normal' },
      { weight: 200, style: 'normal' },
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 800, style: 'normal' },
      { weight: 900, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext'],
    version: 'v11',
    lastModified: '2024-03-14',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Outfit',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap\');',
    fontFamilyCss: 'font-family: \'Outfit\', sans-serif;',
    variable: true,
    description: 'A modern geometric sans-serif typeface designed with a friendly, welcoming spirit and immaculate screen rendering.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'none',
      proportions: 'geometric',
      xHeight: 'high',
      aperture: 'open',
      avgAspect: 0.66,
      strokeWidthRatio: 0.12
    },
    commercialAlternativesFor: ['Futura', 'Avenir Next', 'Gilroy'],
    recommendedPairings: ['Playfair Display', 'Lora', 'Merriweather']
  },
  {
    id: 'work-sans',
    family: 'Work Sans',
    category: 'sans-serif',
    designer: 'Wei Huang',
    variants: [
      { weight: 100, style: 'normal' },
      { weight: 300, style: 'normal' },
      { weight: 400, style: 'normal' },
      { weight: 500, style: 'normal' },
      { weight: 600, style: 'normal' },
      { weight: 700, style: 'normal' },
      { weight: 900, style: 'normal' }
    ],
    subsets: ['latin', 'latin-ext', 'vietnamese'],
    version: 'v19',
    lastModified: '2024-02-22',
    isGoogleFont: true,
    googleFontsUrl: 'https://fonts.google.com/specimen/Work+Sans',
    importUrl: '@import url(\'https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700;900&display=swap\');',
    fontFamilyCss: 'font-family: \'Work Sans\', sans-serif;',
    variable: true,
    description: 'Based loosely on early grotesque fonts like those made by Stephenson Blake, Miller & Richard, and Bauerschen Giesserei.',
    typographicMetrics: {
      serif: 'none',
      contrast: 'low',
      proportions: 'regular',
      xHeight: 'high',
      aperture: 'open',
      avgAspect: 0.63,
      strokeWidthRatio: 0.12
    },
    commercialAlternativesFor: ['Franklin Gothic', 'News Gothic', 'Trade Gothic'],
    recommendedPairings: ['EB Garamond', 'Lora', 'Space Mono']
  }
];
